# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "篇章"
 pageRef = "blog"
 weight = 10

[[main]]
  name = "一念"
  pageRef = "mastodon"
  weight = 11

[[main]]
  name = "如我"
  pageRef = "about"
  weight = 15

[[main]]
  name = "未尽"
  weight = 20

[[main]]
  name = "衡量"
  parent = "未尽"
  pageRef = "statistics"
  weight = 21

[[main]]
  name = "印记"
  parent = "未尽"
  pageRef = "milestone"
  weight = 22

[[main]]
  name = "版权信息"
  parent = "未尽"
  pageRef = "copyright"
  weight = 60

[[main]]
  name = "隐私政策"
  parent = "未尽"
  pageRef = "privacy-policy"
  weight = 70



#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "统计"
  pageRef = "statistics"
  weight = 21

[[footer]]
  name = "里程碑"
  pageRef = "milestone"
  weight = 22

[[footer]]
  name = "版权信息"
  pageRef = "copyright"
  weight = 60

[[footer]]
  name = "隐私政策"
  pageRef = "privacy-policy"
  weight = 70

[[footer]]
  pre = "rss"
  name = "RSS"
  url = ""
  weight = 99

# [[footer]]
#   name = "<div id='notbyai' class='notbyai written'></div>"
#   url = "https://notbyai.fyi"
#   weight = 10

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
